paths:
  uploads: uploads
  static: ''
collections_config:
  pages:
    path: ''
    name: mystique_mainecoons
    icon: wysiwyg
    disable_url: false
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  data:
    path: Data
    icon: data_usage
    disable_url: false
    _inputs:
      $.litters[*].dame:
        type: select
        options:
          allow_create: false
          allow_empty: false
          values: data.queens[*].name
        label: Dame
        cascade: true
      $.litters[*].birth_date:
        type: date
        label: Birth Date
        cascade: true
      $.litters[*].description:
        type: textarea
        label: Description
        cascade: true
      $.litters[*].kittens:
        type: array
        options:
          structures: kitten
        label: Kittens
        cascade: true
      $.litters[*].kittens[*].id:
        label: Kitten ID
        cascade: true
      $.litters[*].kittens[*].name:
        label: Name
        cascade: true
      $.litters[*].kittens[*].sex:
        type: select
        options:
          allow_create: false
          allow_empty: false
          values:
            - Male
            - Female
        label: Sex
        cascade: true
      $.litters[*].kittens[*].color:
        label: Color
        cascade: true
      $.litters[*].kittens[*].status:
        type: select
        options:
          allow_create: false
          allow_empty: false
          values:
            - Available
            - Reserved
            - On Hold
            - Under Review
            - Sold
            - Retained
        label: Availability
        cascade: true
      $.litters[*].kittens[*].price:
        label: Price
        cascade: true
      $.litters[*].kittens[*].image:
        type: image
        label: Image
        cascade: true
      $.litters[*].kittens[*].notes:
        type: textarea
        label: Notes
        cascade: true
      $.queens[*].birthday:
        type: date
        label: Birthday
        cascade: true
      $.kings[*].birthday:
        type: date
        label: Birthday
        cascade: true
      $.news[*].date:
        type: date
        label: Date
        cascade: true
      $.news[*].category:
        type: select
        options:
          allow_create: false
          allow_empty: false
          values:
            - Pregnancy Update
            - Birth Announcement
            - Birthday
            - General Update
        label: Category
        cascade: true
      $.news[*].body:
        type: textarea
        label: Body
        cascade: true
      $.litters[*].sire:
        type: select
        options:
          allow_create:
          allow_empty: false
          values:
          value_key: $.kings[*].name
          preview:
          picker_preview:
          view: text
          picker_view:
          required:
          required_message:
          min_length:
          min_length_message:
          max_length:
          max_length_message:
          pattern:
          pattern_message:
          min_graphemes:
          min_graphemes_message:
          max_graphemes:
          max_graphemes_message:
          min_words:
          min_words_message:
          max_words:
          max_words_message:
          locale:
          empty_type:
        cascade: true
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
_structures:
  kitten:
    style: select
    values:
      - icon: pets
        label: Kitten
        value:
          id: ''
          name: ''
          sex: Male
          color: ''
          status: Available
          price: ''
          image: ''
          notes: ''
timezone: America/Chicago
markdown:
  engine: commonmark
  options:
    xhtml: false
    breaks: false
    linkify: false
    typographer: false
    spaced_lists: false
    sentence_per_line: false
    gfm: false
    code_block_fences: '```'
    escape_snippets_in_code_blocks: false
    treat_indentation_as_code: false
    table: false
    strikethrough: false
    subscript: false
    superscript: false
    heading_ids: false
    attributes: false
